spring:
  application:
    name: dubbo-registry-nacos-consumer-sample

demo:
  service:
    version: 1.0.0

nacos:
  host: 117.78.0.112
  port: 8848
  username: nacos
  password: nacos

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  application:
    name: "consumer"
  protocol:
    port: 20899